import modelJson from "./model.json";
import notebookJson from "./notebook.json";
import type { ModelData, NotebookData } from "./types";

/** Facts recorded in the notebook, generated by analytics/extract_notebook.py. */
export const notebook = notebookJson as unknown as NotebookData;

/** The deployed model, described by analytics/extract_model.py. */
export const model = modelJson as unknown as ModelData;

export const CLASSES = notebook.dataset.classes;

export const NOT_AVAILABLE = "Not available from current experiment";

/** Where the optional evaluation export is served from. */
export const EVAL_URL = `${import.meta.env.BASE_URL}analytics/eval.json`;
